server:
  port: 8080
spring:
  application:
    name: "ApiBackProj"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

  r2dbc:
    database: "base"
    host: "localhost"
    port: 5432
    username: "root"
    password: "1234"
    schema: "public"
    pool:
      initial-size: 12
      max-size: 15
      max-idle-time: 10

    jpa:
      show-sql: true

    sql:
      init:
        mode: always

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"